(load "load.lsp")

(format t "~%-----------------------------------------------------------")
(format t "~%TEST:all_test.lsp: TESTS OF utils")
(load "utils_test.lsp")
(format t "~%-----------------------------------------------------------")
(format t "~%TEST:all_test.lsp: TESTS OF sustitution")
(load "sustitution_test.lsp")
(format t "~%-----------------------------------------------------------")
(format t "~%TEST:all_test.lsp: TESTS OF composition")
(load "composition_test.lsp")
(format t "~%-----------------------------------------------------------")
(format t "~%TEST:all_test.lsp: TESTS OF unification")
(load "unification_test.lsp")