/*****************************************************************************

		Copyright (c) Almazon

 Project:  aLmazon
 FileName: ALMAZON.INC
 Purpose:  Project's global declarations
 Written by: Francisco y Hector
 Comments:
*****************************************************************************/


/*****************************************************************************
			User's Declarations
*****************************************************************************/
global domains
  DB_SELECTOR = browselist_db	% For treebrowser tool
  FILE = fileselector1; fileselector2 % To be edited
